### ISSUE TITLE
Can't load devices

### ISSUE THREAD

**Issue by jeffrigby** [PhysicalGraph/SmartThings-Alfred#3]
I'm able to authenticate to smartthings and when I'm done I get a message that says:

Success
Stopping embedded HTTP server - none.

After this I can't seem to access any of my devices via the "st" prefix. The device.txt file is also empty.

I have a v2 hub and am using the latest version of Alfred.

**Comment by daveismith** [comment]
I'm getting the same issue too.

**Comment by 4loveofpunk** [comment]
I'll make that a 3rd person, no more devices listed and same error.

**Comment by kastork** [comment]
Similar situation with Alfred 3 and v2 hub

1. Migrate to new hub v2, everything working fine from mobile app
2. alfred st_logout (seems to work)
3. afred st_login (seems to work)
4. alfred st_update fails

```
[2016-06-05 05:55:53][ERROR: input.scriptfilter] Code 1: Traceback (most recent call last):
  File "<string>", line 3, in <module>
  File "device_collector.py", line 18, in device_collector
    command = args[-2]
IndexError: list index out of range
[2016-06-05 05:55:57][ERROR: action.script] Traceback (most recent call last):
  File "<string>", line 3, in <module>
  File "refresh_devices.py", line 28, in refresh_devices
    response = urllib2.urlopen(req)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 437, in open
    response = meth(req, response)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 550, in http_response
    'http', request, response, code, msg, hdrs)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 475, in error
    return self._call_chain(*args)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 558, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
urllib2.HTTPError: HTTP Error 403: Forbidden
```

**Comment by kastork** [comment]
Update.

There is one problem in the workflow, but I don't think it is the source of the problem.

In the OSA Script at the end of st_login,

```applescript
set temp to "{query}"
set temp to do shell script "echo " & quoted form of temp & "| tr -d '\\r\\n' "

if temp is "" then
	tell application "Alfred 2" to search "st_login "
else
	do shell script "python get_endpoints.py"
end if
```
It needs to be changed to "Alfred 3"

But this is just internal notification.

**Comment by kastork** [comment]
Update 2

There seems to be something strange taking place in the cloud infrastructure.

When I just go visit https://graph.api.smartthings.com and log in, I see a different set of smart apps than I do if I look at the smart apps when I arrive at the OAuth page during the st_login process.

1. During st_login I arrive at the auth page
2. Instead of trying to auth, click on "My Smart Apps"  This lands me at https://graph.api.smartthings.com/ide/apps
3. In a separate "incognito" window, visit https://graph.api.smartthings.com and log in
4. Click on "My Smart Apps", This lands me at https://graph-na02-useast1.api.smartthings.com/ide/apps

The apps in these locations are different, so I deleted everything and started over.  My Smart Apps at https://graph-na02-useast1.api.smartthings.com/ide/apps now only contains a new instantiation of the Alfred smart app, with OAuth turned on and published for myself.

Now, starting from scratch on Alfred

1. `st_login`
Arrive at https://graph.api.smartthings.com/oauth/confirm_access?...

2. Click on "My Smart Apps", forcing it to load in a new tab.
Arrive at https://graph.api.smartthings.com/ide/apps, which contains NO apps.

3. Return to the tab that has the auth page
select my location and tick two switches

4. Hit "Authorize" button
I now get (after making the applescript change mentioned earlier) a notification center "success" message, and I'm returned to the Afred workflow's success page

At this moment, I have a `token.txt`,  with a token string, an `endpoints.txt`

```
/api/smartapps/installations/8d0c50d2-e5ce-4812-a6b9-449e7c38d0f0
```

and an empty `devices.txt`, as expected.

5. `st_update`

```
2016-06-05 07:46:44][ERROR: input.scriptfilter] Code 1: Traceback (most recent call last):
  File "<string>", line 3, in <module>
  File "device_collector.py", line 18, in device_collector
    command = args[-2]
IndexError: list index out of range
[2016-06-05 07:46:45][utility.debug] '', {}
[2016-06-05 07:46:46][ERROR: action.script] Traceback (most recent call last):
  File "<string>", line 3, in <module>
  File "refresh_devices.py", line 28, in refresh_devices
    response = urllib2.urlopen(req)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 437, in open
    response = meth(req, response)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 550, in http_response
    'http', request, response, code, msg, hdrs)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 475, in error
    return self._call_chain(*args)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 558, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
urllib2.HTTPError: HTTP Error 403: Forbidden
```

**Comment by daveismith** [comment]
It's been a while, but I managed to hack it. It has to do with the cloud URIs that alfred is trying to use. Essentially it appears that smart things may have changed the URIs you need to hit and the app can't get to them anymore. If my recollection is correct it was something to do some extra subdomains that were likely there for load balancing.

I'm not at home with my hub to be able to figure out what exactly was going on, but I can definitely issue commands to ST bulbs using alfred after fixing the URI issue.

**Comment by kastork** [comment]
@daveismith This matches up with what I'm seeing.

But I have to say that this URL `https://graph-na02-useast1.api.smartthings.com` does not look permanent to me.  Is it the right one?

**Comment by daveismith** [comment]
@kastork That's it exactly. To me that looks like it's coming from some sort of load balancer or something. That's why I didn't publish my hack when I did it. That said, I've got a REST endpoint set up for flick buttons and it's been working reliably for 2 months with the same sort of URI so I don't really know. Maybe there's some more redundancy that could be built in to go find that URI again if the operation fails?

**Comment by kastork** [comment]
The docs for web services SmartApps give this example:

```
# This is the URI we will use to get the endpoints once we've received our token
endpoints_uri = 'https://graph.api.smartthings.com/api/smartapps/endpoints'

options = {
  site: 'https://graph.api.smartthings.com',
  authorize_url: '/oauth/authorize',
  token_url: '/oauth/token'
}
```

**Comment by beckje01** [comment]
The URLs will be different per location potentially the external service can hit the one endpoints URL to get the correct URL bases to call. 

If this app is self published you have to make sure publish it in each shard and when starting the oauth flow you need to use the correct client id for the shard matching your location. If you log into the ide and click a location it will direct you to the correct shard for that location.

**Comment by kastork** [comment]
@beckje01 
We're just trying to get your smart app to work under new the conditions.  Looks like we'll need to hack on it quite a bit if it isn't going to be made available officially.

**Comment by beckje01** [comment]
Yeah I was just trying to provide more info to help you along. I don't know the long term plans on this app.

**Comment by kastork** [comment]
Appreciate it...

Thought it would just be some tweaks, but with your pointer and some motivation to read how to build one of these things from scratch it looks like a bigger effort, but still very do-able.  And a good excuse to learn something new.

**Comment by vlaminck** [comment]
If you're up for rebuilding this or just tweaking it to work, we'd be happy to publish whatever you come up with. I would love to see someone pick it up and run with it. Otherwise, it will probably get deprecated and pulled since it's broken.

**Comment by arostad** [comment]
Bump for a working Alfred 3 SmartThings Workflow!

I'll PayPal $20 to anybody that wants to fix it back to 100% working order and give it to vlaminck to publish. It's not a lot but it's better than nothing ☺️

**Comment by ktal90** [comment]
I made a PR (https://github.com/PhysicalGraph/SmartThings-Alfred/pull/4) on this. Simply changing references Alfred 2 to Alfred 3 seems to have brought this workflow to life for me. Give it a try!

**Comment by vlaminck** [comment]
After merging PR #4, this is working for me. I'm closing this issue and can reopen it if others are still experiencing this.
